// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/book.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Publish              string   `protobuf:"bytes,4,opt,name=publish,proto3" json:"publish,omitempty"`
	Introduction         string   `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Number               int64    `protobuf:"varint,6,opt,name=number,proto3" json:"number,omitempty"`
	MaxNumber            int64    `protobuf:"varint,7,opt,name=max_number,json=maxNumber,proto3" json:"max_number,omitempty"`
	ISBN                 string   `protobuf:"bytes,8,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPublish() string {
	if m != nil {
		return m.Publish
	}
	return ""
}

func (m *Book) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *Book) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Book) GetMaxNumber() int64 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

func (m *Book) GetISBN() string {
	if m != nil {
		return m.ISBN
	}
	return ""
}

type GetBookListReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Publish              string   `protobuf:"bytes,3,opt,name=publish,proto3" json:"publish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookListReq) Reset()         { *m = GetBookListReq{} }
func (m *GetBookListReq) String() string { return proto.CompactTextString(m) }
func (*GetBookListReq) ProtoMessage()    {}
func (*GetBookListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{1}
}

func (m *GetBookListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListReq.Unmarshal(m, b)
}
func (m *GetBookListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListReq.Marshal(b, m, deterministic)
}
func (m *GetBookListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListReq.Merge(m, src)
}
func (m *GetBookListReq) XXX_Size() int {
	return xxx_messageInfo_GetBookListReq.Size(m)
}
func (m *GetBookListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListReq proto.InternalMessageInfo

func (m *GetBookListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBookListReq) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetBookListReq) GetPublish() string {
	if m != nil {
		return m.Publish
	}
	return ""
}

type GetBookListRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Books                []*Book  `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookListRsp) Reset()         { *m = GetBookListRsp{} }
func (m *GetBookListRsp) String() string { return proto.CompactTextString(m) }
func (*GetBookListRsp) ProtoMessage()    {}
func (*GetBookListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{2}
}

func (m *GetBookListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListRsp.Unmarshal(m, b)
}
func (m *GetBookListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListRsp.Marshal(b, m, deterministic)
}
func (m *GetBookListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListRsp.Merge(m, src)
}
func (m *GetBookListRsp) XXX_Size() int {
	return xxx_messageInfo_GetBookListRsp.Size(m)
}
func (m *GetBookListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListRsp proto.InternalMessageInfo

func (m *GetBookListRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetBookListRsp) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type AddBooksReq struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBooksReq) Reset()         { *m = AddBooksReq{} }
func (m *AddBooksReq) String() string { return proto.CompactTextString(m) }
func (*AddBooksReq) ProtoMessage()    {}
func (*AddBooksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{3}
}

func (m *AddBooksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBooksReq.Unmarshal(m, b)
}
func (m *AddBooksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBooksReq.Marshal(b, m, deterministic)
}
func (m *AddBooksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBooksReq.Merge(m, src)
}
func (m *AddBooksReq) XXX_Size() int {
	return xxx_messageInfo_AddBooksReq.Size(m)
}
func (m *AddBooksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBooksReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddBooksReq proto.InternalMessageInfo

func (m *AddBooksReq) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type AddBooksRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBooksRsp) Reset()         { *m = AddBooksRsp{} }
func (m *AddBooksRsp) String() string { return proto.CompactTextString(m) }
func (*AddBooksRsp) ProtoMessage()    {}
func (*AddBooksRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{4}
}

func (m *AddBooksRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBooksRsp.Unmarshal(m, b)
}
func (m *AddBooksRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBooksRsp.Marshal(b, m, deterministic)
}
func (m *AddBooksRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBooksRsp.Merge(m, src)
}
func (m *AddBooksRsp) XXX_Size() int {
	return xxx_messageInfo_AddBooksRsp.Size(m)
}
func (m *AddBooksRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBooksRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddBooksRsp proto.InternalMessageInfo

func (m *AddBooksRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddBooksRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type UpdateBooksReq struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBooksReq) Reset()         { *m = UpdateBooksReq{} }
func (m *UpdateBooksReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBooksReq) ProtoMessage()    {}
func (*UpdateBooksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{5}
}

func (m *UpdateBooksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBooksReq.Unmarshal(m, b)
}
func (m *UpdateBooksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBooksReq.Marshal(b, m, deterministic)
}
func (m *UpdateBooksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBooksReq.Merge(m, src)
}
func (m *UpdateBooksReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBooksReq.Size(m)
}
func (m *UpdateBooksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBooksReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBooksReq proto.InternalMessageInfo

func (m *UpdateBooksReq) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type UpdateBooksRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBooksRsp) Reset()         { *m = UpdateBooksRsp{} }
func (m *UpdateBooksRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateBooksRsp) ProtoMessage()    {}
func (*UpdateBooksRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{6}
}

func (m *UpdateBooksRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBooksRsp.Unmarshal(m, b)
}
func (m *UpdateBooksRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBooksRsp.Marshal(b, m, deterministic)
}
func (m *UpdateBooksRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBooksRsp.Merge(m, src)
}
func (m *UpdateBooksRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateBooksRsp.Size(m)
}
func (m *UpdateBooksRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBooksRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBooksRsp proto.InternalMessageInfo

func (m *UpdateBooksRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateBooksRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteBooksReq struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBooksReq) Reset()         { *m = DeleteBooksReq{} }
func (m *DeleteBooksReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBooksReq) ProtoMessage()    {}
func (*DeleteBooksReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{7}
}

func (m *DeleteBooksReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBooksReq.Unmarshal(m, b)
}
func (m *DeleteBooksReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBooksReq.Marshal(b, m, deterministic)
}
func (m *DeleteBooksReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBooksReq.Merge(m, src)
}
func (m *DeleteBooksReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBooksReq.Size(m)
}
func (m *DeleteBooksReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBooksReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBooksReq proto.InternalMessageInfo

func (m *DeleteBooksReq) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type DeleteBooksRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBooksRsp) Reset()         { *m = DeleteBooksRsp{} }
func (m *DeleteBooksRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteBooksRsp) ProtoMessage()    {}
func (*DeleteBooksRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20c41575ca1f0b3, []int{8}
}

func (m *DeleteBooksRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBooksRsp.Unmarshal(m, b)
}
func (m *DeleteBooksRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBooksRsp.Marshal(b, m, deterministic)
}
func (m *DeleteBooksRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBooksRsp.Merge(m, src)
}
func (m *DeleteBooksRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteBooksRsp.Size(m)
}
func (m *DeleteBooksRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBooksRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBooksRsp proto.InternalMessageInfo

func (m *DeleteBooksRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteBooksRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Book)(nil), "book.Book")
	proto.RegisterType((*GetBookListReq)(nil), "book.GetBookListReq")
	proto.RegisterType((*GetBookListRsp)(nil), "book.GetBookListRsp")
	proto.RegisterType((*AddBooksReq)(nil), "book.AddBooksReq")
	proto.RegisterType((*AddBooksRsp)(nil), "book.AddBooksRsp")
	proto.RegisterType((*UpdateBooksReq)(nil), "book.UpdateBooksReq")
	proto.RegisterType((*UpdateBooksRsp)(nil), "book.UpdateBooksRsp")
	proto.RegisterType((*DeleteBooksReq)(nil), "book.DeleteBooksReq")
	proto.RegisterType((*DeleteBooksRsp)(nil), "book.DeleteBooksRsp")
}

func init() { proto.RegisterFile("protocol/book.proto", fileDescriptor_c20c41575ca1f0b3) }

var fileDescriptor_c20c41575ca1f0b3 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x1f, 0xfd, 0x7a, 0x91, 0xa2, 0x4f, 0x91, 0x25, 0x20, 0x84, 0x9c, 0x7a, 0x6a, 0x21,
	0x05, 0x2f, 0x3d, 0x59, 0x44, 0x11, 0xa4, 0x87, 0x88, 0x5e, 0x25, 0x69, 0x16, 0x1b, 0xda, 0x64,
	0x63, 0xb2, 0x81, 0xfe, 0x47, 0xff, 0x8d, 0xbf, 0x40, 0x76, 0x93, 0x94, 0xac, 0xa4, 0x60, 0x6f,
	0xef, 0xcd, 0x64, 0x76, 0x76, 0x66, 0x09, 0x5c, 0x65, 0x39, 0xe3, 0x6c, 0xcd, 0x76, 0xb3, 0x90,
	0xb1, 0xed, 0x54, 0x6e, 0x68, 0x8a, 0xd9, 0xfd, 0xd6, 0xc0, 0x5c, 0x32, 0xb6, 0xc5, 0x31, 0xe8,
	0x71, 0x44, 0x34, 0x47, 0x9b, 0x18, 0xbe, 0x1e, 0x47, 0x88, 0x60, 0xa6, 0x41, 0x42, 0x89, 0xee,
	0x68, 0x93, 0x91, 0x2f, 0x67, 0xbc, 0x81, 0x7e, 0x50, 0xf2, 0x0d, 0xcb, 0x89, 0x21, 0xd1, 0x7a,
	0x43, 0x02, 0x83, 0xac, 0x0c, 0x77, 0x71, 0xb1, 0x21, 0xa6, 0x24, 0x9a, 0x15, 0x5d, 0x38, 0x8f,
	0x53, 0x9e, 0xb3, 0xa8, 0x5c, 0xf3, 0x98, 0xa5, 0xa4, 0x27, 0x69, 0x05, 0x13, 0xa7, 0xa6, 0x65,
	0x12, 0xd2, 0x9c, 0xf4, 0xa5, 0x7b, 0xbd, 0xe1, 0x2d, 0x40, 0x12, 0xec, 0x3f, 0x6a, 0x6e, 0x20,
	0xb9, 0x51, 0x12, 0xec, 0x57, 0x15, 0x8d, 0x60, 0x3e, 0xbf, 0x2e, 0x57, 0x64, 0x58, 0x5d, 0x50,
	0xcc, 0xee, 0x3b, 0x8c, 0x9f, 0x28, 0x17, 0x79, 0x5e, 0xe2, 0x82, 0xfb, 0xf4, 0xeb, 0x10, 0x43,
	0xeb, 0x8c, 0xa1, 0x1f, 0x8b, 0x61, 0x28, 0x31, 0xdc, 0x47, 0xf5, 0xdc, 0x22, 0x13, 0xe7, 0xae,
	0x59, 0x44, 0xeb, 0xc2, 0xe4, 0x8c, 0x0e, 0xf4, 0x44, 0xa7, 0x05, 0xd1, 0x1d, 0x63, 0x62, 0x79,
	0x30, 0x95, 0x6d, 0x0b, 0x95, 0x5f, 0x11, 0xee, 0x0c, 0xac, 0xfb, 0x28, 0x12, 0x48, 0x21, 0x2e,
	0x77, 0x10, 0x68, 0xc7, 0x04, 0xf3, 0x96, 0xe0, 0x88, 0xeb, 0x05, 0x18, 0x49, 0xf1, 0x59, 0x47,
	0x11, 0xa3, 0xeb, 0xc1, 0xf8, 0x2d, 0x8b, 0x02, 0x4e, 0x4f, 0x30, 0xba, 0x53, 0x35, 0xa7, 0x78,
	0x3d, 0xd0, 0x1d, 0x3d, 0xd5, 0xab, 0xad, 0xf9, 0xaf, 0x97, 0xf7, 0xa3, 0x41, 0x4f, 0x4a, 0x70,
	0x01, 0x56, 0xeb, 0x3d, 0xf0, 0xba, 0xf2, 0x50, 0x9f, 0xde, 0xee, 0x40, 0x8b, 0xcc, 0x3d, 0x43,
	0x0f, 0x86, 0x4d, 0xa7, 0x78, 0x59, 0x7d, 0xd3, 0x7a, 0x14, 0xfb, 0x2f, 0x24, 0x35, 0x0b, 0xb0,
	0x5a, 0xf5, 0x34, 0x86, 0x6a, 0xcb, 0x76, 0x07, 0xda, 0x88, 0x5b, 0x79, 0x1b, 0xb1, 0x5a, 0x9b,
	0xdd, 0x81, 0x0a, 0x71, 0xd8, 0x97, 0x7f, 0xeb, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xd6,
	0x11, 0xce, 0xc4, 0x03, 0x00, 0x00,
}
