registry_addr = "121.5.238.116:2379"
[logger]
    Path   = "/tmp/log/server"
    Level  = "all"
    Stdout = true

[database]
    [[database.default]]
        link  = "mysql:root:123456@tcp(159.75.125.159:3307)/library"
        role  = "master"
        debug = true

[database.logger]
    Path   = "/tmp/log/sql"
    Level  = "all"
    Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link = "mysql:root:123456@tcp(159.75.125.159:3307)/library"
